### ISSUE TITLE
Feature: Export posibility of all map models

### ISSUE THREAD

**Issue by BogdanDumi** [SteamDatabase/ValveResourceFormat#268] opened 2020-07-17 12:32 UTC
- when a map it's opened (dota 2 map) to have the posibility to export entire world (to decompile all vmdl_c references from entire map)
or
- to have the posibility to select one or more entities (from rendered interface -> like tree, stairs, ground, etc) and with right click to decompile and export

**Comment by xPaw** [comment] 2020-07-17 12:35
Duplicate of #232, #251 and #180

**Closed by xPaw** 2020-07-17 12:35 UTC
