### ISSUE TITLE
gltf conversion export stops halfway/incomplete ?

### ISSUE THREAD

**Issue by Ruuubickk** [SteamDatabase/ValveResourceFormat#255] opened 2020-07-11 11:08 UTC
The new Anti-Mage persona just came out on Dota 2, and the model export through source IO worked perfectly, so i thought i'd use VRF to export the scene where the model is presented.

It looks great in the VRF viewer, but the vmdl converted as a gltf doesn't import the majority of texture, most pieces of the scene and doesn't assign the materials to the meshes properly, scale is also 2x what it should be:

![blender_2vLarQ19TG](https://user-images.githubusercontent.com/44787492/87222456-0d996200-c374-11ea-8d33-a4a26aa931b5.png)
![VRF_oY578bYL3s](https://user-images.githubusercontent.com/44787492/87222472-1d18ab00-c374-11ea-98e6-26b96edb2879.png)
![explorer_0TxHCNeijY](https://user-images.githubusercontent.com/44787492/87222481-273aa980-c374-11ea-84fd-dd89c9822b7e.png)

Dota 2 `game/dota/pak01_dir/models/heroes/antimage_female/debut/lm_am_debut_temple_interior.vmdl_c`

Expected behavior would be to end up with the same scene pieces and correctly applied materials

Using latest stable version of VRF on Windows 10

Output gltf is 35KB compared to 890KB vmdl.

**Comment by xPaw** [comment] 2020-07-11 11:30
Testing on master, appears to be a duplicate of #248

**Closed by xPaw** 2020-07-11 11:30 UTC

**Comment by xPaw** [comment] 2020-07-11 12:13
Try latest unstable build, it should work now.
