### ISSUE TITLE
have trouble open files ( i'm using window 7 pro x64 )

### ISSUE THREAD

**Issue by phamtheson01** [SteamDatabase/ValveResourceFormat#127] opened 2019-05-10 02:42 UTC
![image](https://user-images.githubusercontent.com/45394243/57498889-d8c0f380-7307-11e9-9814-454e4a4d9b75.png)

**Comment by xPaw** [comment] 2019-05-10 14:18
Duplicate of #121

**Closed by xPaw** 2019-05-10 14:18 UTC
