### ISSUE TITLE
"Object reference not set to an object" error on latest Dota 2 model export/decompiling

### ISSUE THREAD

**Issue by Ruuubickk** [SteamDatabase/ValveResourceFormat#343] opened 2021-04-10 01:09 UTC
### Describe the bug

Trying to decompile as gltf/glb the latest model from Dota 2 (Dawnbreaker) results in this 

```
[03:04:55.608] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.GltfModelExporter.<ExportToFile>g__AddMeshNode|14_0(String name, Mesh mesh, Skeleton skeleton, <>c__DisplayClass14_0& )
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model)
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __)
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

### What Valve game does this happen in

Dota 2

### Reference file in a Valve game

C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\pak01.vpk:models\heroes\dawnbreaker\dawnbreaker.vmdl_c

### Expected behavior

Model can be decompiled like all other models can,

### What version of VRF are you using? On what platform?

0.1.7 Windows 10

**Comment by xPaw** [comment] 2021-04-10 08:46
I fixed that, but there's an issue with animation exporting:
```
ystem.AggregateException: One or more errors occurred. (value)
 ---> System.NotFiniteNumberException: value
   at SharpGLTF.Memory.FloatingAccessor.set_Item(Int32 rowIndex, Int32 subIndex, Single value)
   at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
   at SharpGLTF.Schema2.AnimationSampler._CreateOutputAccessor(IReadOnlyList`1 output)
   at SharpGLTF.Schema2.AnimationSampler.SetKeys(IReadOnlyDictionary`2 keyframes)
   at SharpGLTF.Schema2.Animation.CreateRotationChannel(Node node, IReadOnlyDictionary`2 keyframes, Boolean linear)
   at ValveResourceFormat.IO.GltfModelExporter.<ExportToFile>g__AddMeshNode|15_0(String name, Mesh mesh, Skeleton skeleton, <>c__DisplayClass15_0& ) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 107
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 127
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass0_0.<Export>b__0(Object _, EventArgs __) in D:\GitHub\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 81
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\GitHub\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by xPaw** [comment] 2021-04-10 08:50
Closing as a duplicate of #309 now.

**Closed by xPaw** 2021-04-10 08:50 UTC
Labels: bug
