### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by xGitHubUser999x** [SteamDatabase/ValveResourceFormat#357] opened 2021-07-04 11:43 UTC
### Describe the bug

When I double click the left mouse button a hoodwink.vmdl_c file an "Unable to read beyond the end of the stream" error appears. If you click on the 'Continue' button, it opens a tab hoodwink.vmdl_c with emty subtab MODEL.

```
************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt16()
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ReadSegment(Int64 frame, IKeyValueCollection segment, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, Frame& outFrame) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 225
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ConstructFromDesc(IKeyValueCollection animDesc, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, IKeyValueCollection[] segmentArray) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 190
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation..ctor(IKeyValueCollection animDesc, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, IKeyValueCollection[] segmentArray) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 28
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.<>c__DisplayClass17_0.<FromData>b__0(IKeyValueCollection anim) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 44
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at ValveResourceFormat.ResourceTypes.Model.GetEmbeddedAnimations() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\Model.cs:line 109
   at GUI.Types.Renderer.ModelSceneNode.LoadAnimations() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\ModelSceneNode.cs:line 214
   at GUI.Types.Renderer.ModelSceneNode..ctor(Scene scene, Model model, String skin, Boolean loadAnimations) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\ModelSceneNode.cs:line 67
   at GUI.Types.Renderer.GLModelViewer.LoadScene() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLModelViewer.cs:line 74
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLSceneViewer.cs:line 85
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Controls\GLViewerControl.cs:line 246
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Private.CoreLib.dll
----------------------------------------
VRF
    Assembly Version: 0.1.9.0
    Win32 Version: 0.1.9.731
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/VRF.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 5.0.7.0
    Win32 Version: 5.0.721.26307
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 5.0.7.0
    Win32 Version: 5.0.721.26307
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Collections.Specialized.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Console
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Console.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.IO.FileSystem.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 5.0.0.2
    Win32 Version: 5.0.421.11614
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.721.26307
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/Accessibility.dll
----------------------------------------
System.Linq
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.ComponentModel.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Collections.Concurrent.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Collections.NonGeneric.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Resources.Extensions.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.ObjectModel.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Diagnostics.Process.dll
----------------------------------------
ValveKeyValue
    Assembly Version: 0.5.0.0
    Win32 Version: 0.5.0.4
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/ValveKeyValue.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Collections
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Collections.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Threading
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Threading.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Text.RegularExpressions.dll
----------------------------------------
ValvePak
    Assembly Version: 1.0.2.35
    Win32 Version: 1.0.2.35
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/ValvePak.dll
----------------------------------------
ValveResourceFormat
    Assembly Version: 0.1.9.0
    Win32 Version: 0.1.9.731
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/ValveResourceFormat.dll
----------------------------------------
SkiaSharp
    Assembly Version: 2.80.0.0
    Win32 Version: 2.80.2.0
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/SkiaSharp.dll
----------------------------------------
SkiaSharp.Views.Desktop.Common
    Assembly Version: 2.80.0.0
    Win32 Version: 2.80.2.0
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/SkiaSharp.Views.Desktop.Common.dll
----------------------------------------
System.Windows.Forms.Design
    Assembly Version: 5.0.7.0
    Win32 Version: 5.0.721.26307
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Windows.Forms.Design.dll
----------------------------------------
ZstdSharp
    Assembly Version: 0.3.0.0
    Win32 Version: 0.3.0.0
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/ZstdSharp.dll
----------------------------------------
K4os.Compression.LZ4
    Assembly Version: 1.2.6.0
    Win32 Version: 1.2.6
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/K4os.Compression.LZ4.dll
----------------------------------------
OpenTK
    Assembly Version: 3.3.1.0
    Win32 Version: 3.3.1
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/OpenTK.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/OpenTK.GLControl.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Linq.Expressions.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Private.CoreLib.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.IO.MemoryMappedFiles.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.IO.Compression.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/Microsoft.Win32.Registry.dll
----------------------------------------
System.Drawing
    Assembly Version: 5.0.7.0
    Win32 Version: 5.0.721.26307
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Drawing.dll
----------------------------------------
SharpGLTF.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/SharpGLTF.Core.dll
----------------------------------------
SharpGLTF.Toolkit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/SharpGLTF.Toolkit.dll
----------------------------------------
System.Text.Json
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Text.Json.dll
----------------------------------------
System.Memory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Memory.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 5.0.0.1
    Win32 Version: 5.0.721.25508
    CodeBase: file:///C:/Users/Username/AppData/Local/Temp/.net/VRF/pptqb30n.dwq/System.Text.Encodings.Web.dll
----------------------------------------

************** JIT Debugging **************
```

### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

D:\Steam\SteamApps\common\dota 2 beta\game\dota\pak01_dir.vpk\models\heroes\hoodwink\hoodwink.vmdl_c

### Expected behavior

I expect when I double click the left mouse button a hoodwink.vmdl_c file, no error should appear and the MODEL subtab should display the loaded model that I can export.

### What version of VRF are you using? On what platform?

Version of VRF: 0.1.9.731                         Platform: Windows 8.1 x64

**Comment by xPaw** [comment] 2021-07-04 13:33
Closing as a duplicate of #358 which has the relevant info of the bug.

**Closed by xPaw** 2021-07-04 13:33 UTC
Labels: bug
