### ISSUE TITLE
Support Source2 Mobile VTEX_C

### ISSUE THREAD

**Issue by MattFiler** [SteamDatabase/ValveResourceFormat#145] opened 2019-06-20 19:45 UTC
With the release of Underlords on mobile, it seems Source2 uses a slightly modified VTEX_C file format.

Here's a [link to an example file from mobile](https://drive.google.com/file/d/1A35qUsG7UyTHJFQNAm8nAKu3lqu4rHje/view?usp=sharing), and [its PC counterpart](https://drive.google.com/file/d/1eXDg6MO4m2NEboWmm5GN22Y4RuJ2wjgU/view?usp=sharing).

**Comment by xPaw** [comment] 2019-06-20 19:45
Duplicate of #144

**Closed by xPaw** 2019-06-20 19:45 UTC
