### ISSUE TITLE
cannot open vtex_c file

### ISSUE THREAD

**Issue by phamtheson01** [SteamDatabase/ValveResourceFormat#121] opened 2019-01-26 08:47 UTC

**Comment by phamtheson01** [comment] 2019-01-26 08:48
another request: 
1.add option to export vmesh_c to smd
2.add option to export vanim_c to smd

**Comment by xPaw** [comment] 2019-01-26 08:50
"cannot open vtex_c file" literally doesn't say anything. If you are trying to report a bug provide clear details, what issue you have and what file is causing it.

The other comment is a duplicate of #102

**Comment by phamtheson01** [comment] 2019-01-26 08:51
i'm uploading the details :)

**Closed by xPaw** 2019-01-26 08:50 UTC

**Comment by phamtheson01** [comment] 2019-01-26 08:55
updated the detail

**Comment by phamtheson01** [comment] 2019-01-26 08:56
i'm using the newest version

**Comment by xPaw** [comment] 2019-01-26 09:40
Sounds like you have missing dlls, try to download last version or the one before if that doesn't work.

**Comment by AveYo** [comment] 2019-01-27 21:59
It's the skiasharp external library, has a bug with not copying all dlls in the release folder.
Should be fixed in newer versions but that requires updating the project files
@OP just search for the libskiasharp.dll is around 6MB size and place it in the release directory

**Comment by xPaw** [comment] 2019-01-29 10:18
@AveYo SkiaSharp dlls are in the VRF GUI.zip.
