### ISSUE TITLE
Multiple glTF/glb model components are not imported as a whole entity

### ISSUE THREAD

**Issue by BogdanDumi** [SteamDatabase/ValveResourceFormat#514] opened 2023-02-09 11:57 UTC
### Describe the bug

Actions:
1. Decompile an entire folder with multiple models (E.g.: Dota 2 pak01_dir.vpk -> models -> heroes -> drow folder )
2. In Blender import all glTF/glb files (see picture1)

Observed behaviour:
1. Base model is not aligned with the rest of components
2. Animations act only on base model and not over all components

Expected behaviour:
1. Base model should be aligned with the rest of components
2. Animations should act on all components (see picture2_original_model_from_valve)
3. Child components(armatures) should have a relation with base_armature (i guess)
![image](https://user-images.githubusercontent.com/68294340/217805451-b7f91545-42a0-4e5a-8874-d759d49e31ae.png)
![image](https://user-images.githubusercontent.com/68294340/217805757-0e66244a-ba72-4d3b-a690-91a4d28ffc65.png)

### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

pak01_dir.vpk -> models -> heroes -> drow folder

### Expected behavior

1. Base model should be aligned with the rest of components
2. Animations should act on all components (see picture2_original_model_from_valve)
3. Child components(armatures) should have a relation with base_armature (i guess)

### What version of VRF are you using? On what platform?

0.3.0.1412

**Comment by moofMonkey** [comment] 2023-02-09 13:20
Duplicate of #251

They're not supposed to be automatically combined, as otherwise you could accidentally combine parts that were meant for other models, especially when exporting large folders such as `models/` or `models/heroes/`.

There should probably be a separate dialog for that, as you might easily want separate parts from different folders, example being econ wearables - e.g. something from `models/items/` and the rest from `models/heroes/`.

**Closed by moofMonkey** 2023-02-09 13:20 UTC
Labels: bug

**Comment by BogdanDumi** [comment] 2023-02-09 15:51
Then can be changed to feature task. When you are exporting 2 or more models to have the option to merge it in a single one. Just an idea.

**Comment by kristiker** [comment] 2023-02-09 17:24
I'm assuming they are bonemerged in engine. If so then just look up how to bonemerge in blender?

**Comment by BogdanDumi** [comment] 2023-02-09 18:33
I found how to merge all components by changing Objecct -> Modifier -> Armature -> Relations -> Parent to base object(E.g.: see attached image). The easiest way is to create a python script for multiple models to do this.
![image](https://user-images.githubusercontent.com/68294340/217903367-a8ade18f-ef31-4b96-aded-d08dc22b8260.png)
