### ISSUE TITLE
Exception: System.NotFiniteNumberException: value

### ISSUE THREAD

**Issue by Lifeismana** [SteamDatabase/ValveResourceFormat#575] opened 2023-07-06 22:51 UTC
### Describe the bug

File does not export

### Relevant log output or exception with stacktrace

```shell
Exception: System.NotFiniteNumberException: value
   at SharpGLTF.Memory.Vector3Array.set_Item(Int32 index, Vector3 value)
   at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
   at SharpGLTF.Schema2.AnimationSampler._CreateOutputAccessor(IReadOnlyList`1 output)
   at SharpGLTF.Schema2.AnimationSampler.SetKeys(IReadOnlyDictionary`2 keyframes)
   at SharpGLTF.Schema2.Animation.CreateScaleChannel(Node node, IReadOnlyDictionary`2 keyframes, Boolean linear)
   at ValveResourceFormat.IO.GltfModelExporter.LoadModel(ModelRoot exportedModel, Scene scene, Model model, String name, Matrix4x4 transform, IDictionary`2 loadedMeshDictionary, String skinName) in /data/ValveResourceFormat/ValveResourceFormat/IO/GltfModelExporter.cs:line 507
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in /data/ValveResourceFormat/ValveResourceFormat/IO/GltfModelExporter.cs:line 356
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in /data/ValveResourceFormat/ValveResourceFormat/IO/GltfModelExporter.cs:line 145
   at Decompiler.Decompiler.DumpVPK(String parentPath, Package package, String type, Dictionary`2 manifestData) in /data/ValveResourceFormat/Decompiler/Decompiler.cs:line 916
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

weapons/models/elite/weapon_pist_elite.vmdl_c (game/csgo/pak01)

### Expected behavior

File should export as gltf

### What version of VRF are you using? On what platform?

4.0.0+8ae513f1ac296b8dba353521b9f597da0282e2e4 linux

**Comment by xPaw** [comment] 2023-07-07 08:02
Duplicate of #570

**Closed by xPaw** 2023-07-07 08:02 UTC
Labels: bug
