### ISSUE TITLE
image exported with gltf missing transparent

### ISSUE THREAD

**Issue by phamtheson01** [SteamDatabase/ValveResourceFormat#269] opened 2020-07-18 06:37 UTC
![image](https://user-images.githubusercontent.com/45394243/87846661-bbb88500-c8fb-11ea-8dcf-f89ba6dc29ae.png)

**Comment by xPaw** [comment] 2020-07-18 07:14
We don't handle transparency there just yet because it's not trivial. Duplicate of #212

**Closed by xPaw** 2020-07-18 07:14 UTC
