### ISSUE TITLE
new issues with vsndevts_c not being properly converted

### ISSUE THREAD

**Issue by mdiller** [SteamDatabase/ValveResourceFormat#123] opened 2019-01-30 08:30 UTC
I've been using the decompiler for a while, and it has been working fine on the dota 2 vpk. I've recently run into issues with a few of the updated vsndevts_c files that seem to have a very different format than the others. The decompiler gives me the message "Decompiler for resource type vsndevts_c not implemented, extracting as-is", and when I went and looked at the exception it was this:
```
System.NotImplementedException: WriteText() in ResourceData
   at ValveResourceFormat.Blocks.ResourceData.WriteText(IndentedTextWriter writer)
   at ValveResourceFormat.Block.ToString()
   at Decompiler.Decompiler.DumpVPK(Package package, String type, String newType) in C:\Development\outside_projects\ValveResourceFormat\Decompiler\Program.cs:line 723
```
This might be related to another issue but I don't see any recent issues open about this so I figured I'd open one in case someone might know something about it. I've attached 2 files. One that works, and one that doesn't. The riki one works, and the rubick one gives the error above.

[vsndevts_examples.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/2811582/vsndevts_examples.zip)

**Comment by xPaw** [comment] 2019-01-30 08:32
Duplicate of #38

**Closed by xPaw** 2019-01-30 08:32 UTC
