### ISSUE TITLE
Cannot allocate a buffer of size 2262462938 (also way to many .bin files)

### ISSUE THREAD

**Issue by Unitytheproto** [SteamDatabase/ValveResourceFormat#387] opened 2021-11-15 17:02 UTC
### Describe the bug

After several hours of waiting and 11.5 MILLION .bin files it errored out with a buffer issue.

Heres the full error code:

[10:45:16.729] System.AggregateException: One or more errors occurred. (Cannot allocate a buffer of size 2262462938.)
 ---> System.OutOfMemoryException: Cannot allocate a buffer of size 2262462938.
   at System.Buffers.ArrayBufferWriter`1.ThrowOutOfMemoryException(UInt32 capacity)
   at System.Buffers.ArrayBufferWriter`1.CheckAndResizeBuffer(Int32 sizeHint)
   at System.Buffers.ArrayBufferWriter`1.GetMemory(Int32 sizeHint)
   at System.Text.Json.Utf8JsonWriter.Grow(Int32 requiredSize)
   at System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(Double value)
   at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Double value)
   at SharpGLTF.IO._JSonSerializationExtensions.TryWriteValue(Utf8JsonWriter writer, Object value)
   at SharpGLTF.IO.JsonSerializable._SerializeValue(Utf8JsonWriter writer, Object value)
   at SharpGLTF.IO.JsonSerializable.SerializeProperty[T](Utf8JsonWriter writer, String name, IReadOnlyList`1 collection, Nullable`1 minItems)
   at SharpGLTF.Schema2.Accessor.SerializeProperties(Utf8JsonWriter writer)
   at SharpGLTF.IO.JsonSerializable.Serialize(Utf8JsonWriter writer)
   at SharpGLTF.IO.JsonSerializable.SerializeProperty[T](Utf8JsonWriter writer, String name, IReadOnlyList`1 collection, Nullable`1 minItems)
   at SharpGLTF.Schema2.ModelRoot.SerializeProperties(Utf8JsonWriter writer)
   at SharpGLTF.IO.JsonSerializable.Serialize(Utf8JsonWriter writer)
   at SharpGLTF.Schema2.ModelRoot._WriteJSON(Stream sw, JsonWriterOptions options)
   at SharpGLTF.Schema2.WriteContext.WriteTextSchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.SaveGLTF(String filePath, WriteSettings settings)
   at SharpGLTF.Schema2.ModelRoot.Save(String filePath, WriteSettings settings)
   at ValveResourceFormat.IO.GltfModelExporter.WriteModelFile(ModelRoot exportedModel, String filePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 451
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 110
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 88
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

### What Valve game does this happen in

Half Life: Alyx

### Reference file in a Source 2 game

a2_hideout.vpk/maps/a2_hideout/world.vwrld_c

### Expected behavior

To export the hideout map from half life alyx with all of its textures and not spam 11.5 million files

### What version of VRF are you using? On what platform?

v0.1.10.832  Windows 10

**Comment by xPaw** [comment] 2021-11-15 17:03
Duplicate of #379

**Closed by xPaw** 2021-11-15 17:03 UTC
Labels: bug
