### ISSUE TITLE
GUI & Decompiler exporting to GLTF textures are missing alpha

### ISSUE THREAD

**Issue by GoranKovac** [SteamDatabase/ValveResourceFormat#326] opened 2021-02-19 16:23 UTC
### Describe the bug
In GUI version if you export model to GLTF textures are missing alpha.
Same thing is with decompiler when using --gltf_export_materials.
Result:
![gltf_export](https://user-images.githubusercontent.com/19614757/108531563-1b826e80-72d7-11eb-8403-239fade22801.png)

If same textures are converted manually with following:
Decompiler.exe -i "C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\pak01_dir.vpk" -o "C:\test" -d -e vtex_c -f materials/models/heroes/abaddon

Texures have alpha, result:
![manual_export](https://user-images.githubusercontent.com/19614757/108531577-20dfb900-72d7-11eb-92a7-8b11219218a2.png)

### Reference file in a Valve game
Dota 2 pak01.dir (any asset)
pak01.dir /models
pak01.dir /materials/models

### Expected behavior
Textures have alpha information

### Version info
Decompiler 0.1.7.1445 - latest unstable (also present in stable version)
Same with GUI (latest unstable and stable)

**Comment by xPaw** [comment] 2021-02-19 16:58
Duplicate of #212 and #194

**Closed by xPaw** 2021-02-19 16:58 UTC
