### ISSUE TITLE
MeshPrimitive[0] NORMAL: 3592 must be equal to 14371.

### ISSUE THREAD

**Issue by thouravi** [SteamDatabase/ValveResourceFormat#589] opened 2023-08-06 07:14 UTC
### Describe the bug

I got this error while trying to decompile and export weapon model C4.
weapons/models/c4/weapon_c4.vmdl_c

### Relevant log output or exception with stacktrace

```shell
[12:39:20.330] Writing model to file 'weapon_c4.glb'...
[12:39:20.354] System.AggregateException: One or more errors occurred. (MeshPrimitive[0] NORMAL: 3592 must be equal to 14371.)
 ---> SharpGLTF.Validation.SchemaException: MeshPrimitive[0] NORMAL: 3592 must be equal to 14371.
   at SharpGLTF.Validation.ValidationContext._SchemaThrow(ValueLocation pname, String msg)
   at SharpGLTF.Validation.ValidationContext.AreEqual[TValue](ValueLocation parameterName, TValue value, TValue expected)
   at SharpGLTF.Schema2.MeshPrimitive.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ExtraProperties.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.Mesh.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ExtraProperties.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.WriteContext._ValidateBeforeWriting(ModelRoot model)
   at SharpGLTF.Schema2.WriteContext.WriteBinarySchema2(String baseName, ModelRoot model)
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 348
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 126
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 312
   at GUI.Forms.ExtractProgressForm.ExtractFilesAsync(Queue`1 filesToExtract) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 231
   at GUI.Forms.ExtractProgressForm.<OnShown>b__15_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 103
   --- End of inner exception stack trace ---
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

weapons/models/c4/weapon_c4.vmdl_c

### Expected behavior

Properly decompile and export.

### What version of VRF are you using? On what platform?

VRF v4.0.2078

**Comment by xPaw** [comment] 2023-08-06 07:32
Duplicate of #585

**Closed** 2023-08-06 07:33 UTC
Labels: bug
